builders:
  systemBuilder:
    import: "package:dartemis_builder/builder.dart"
    builder_factories:
      - systemBuilder
    build_extensions:
      .dart:
        - "dartemis_builder.g.dart"
    build_to: source
    auto_apply: root_package