builders:
  systemBuilder:
    import: "package:dartemis_builder/builder.dart"
    builder_factories: ["systemBuilder"]
    build_extensions: {".dart": ["dartemis_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]