name: dartemis_builder
description: A builder for use with dartemis to generate code that initializes EntitySystems and Managers.
version: 0.1.0-dev
homepage: https://github.com/denniskaselow/dartemis_builder
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.0.0
  build_config: '>=0.3.0 <0.5.0'
  source_gen: ^0.9.0
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
      ref: entityToInt

dev_dependencies:
  build_test: ^1.0.0
  test: ^1.2.0
  mockito: ^4.0.0
