name: dartemis_builder
description: A builder for use with dartemis to generate code that initializes EntitySystems and Managers.
version: 0.3.1
homepage: https://github.com/denniskaselow/dartemis_builder

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.0.0
  build_config: ^1.0.0
  dartemis: ^0.9.0
  source_gen: ^1.0.0

dev_dependencies:
  build_test: ^2.0.0
  mockito: ^5.0.0
  test: ^1.16.0
