name: dartemis_builder
description: A builder to generate code that initializes EntitySystems and Managers.
version: 0.0.1-dev
homepage: https://github.com/denniskaselow/dartemis_builder
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^0.12.7
  build_config: ^0.3.1
  source_gen: ^0.9.0
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git

dev_dependencies:
  build_test: ^0.10.2
  test: ^1.2.0
  mockito: ^3.0.0
