name: dartemis_builder
description: A builder for use with dartemis to generate code that initializes EntitySystems and Managers.
version: 0.1.1
homepage: https://github.com/denniskaselow/dartemis_builder

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.0 <0.41.0'
  build: ^1.0.0
  build_config: '>=0.3.0 <0.5.0'
  dartemis: ^0.8.0
  source_gen: ^0.9.0

dev_dependencies:
  build_test: ^1.0.0
  mockito: ^4.0.0
  test: ^1.2.0
